name: 'hello'
description: 'Hello action'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: false
    default: 'World'
runs:
  using: "docker"
  image: 'Dockerfile'
outputs:
  time:
    description: 'The time we greeted you'


